version: "3"
services:
    nginx:
        image: nginx
        build:
            context: ./nginx
            dockerfile: Dockerfile
        ports:
            - 8080:8080
        restart: always
    flask:
        depends_on:
            - nginx
        image: flask
        build: ./flask
        restart: always
        env_file: ./flask/.env

# docker-compose up -d --build
# docker-compose down
