# Docker Compose configuration with separate staging and production Solr cores
# This is an enhanced version that creates both cores automatically

services:
  solr:
    container_name: sdoh-solr
    image: 'solr:9.7.0-slim'
    ports:
    - 8983:8983
    healthcheck:
      test: ["CMD-SHELL", "bin/solr status"]
      interval: 10s
      retries: 5
      start_period: 120s
      timeout: 10s
    volumes:
      - ./solr/web.xml:/opt/solr-9.7.0-slim/server/solr-webapp/webapp/WEB-INF/web.xml
      - ./solr/solr.in.sh:/etc/default/solr.in.sh
      - ./solr:/solr-configset
      - solr-data:/var/solr
    command: 
      - '/bin/sh'
      - '-c'
      - |
        # Start Solr in background
        solr-precreate blacklight-core-stage /solr-configset &
        PRECREATE_PID=$!
        
        # Wait for Solr to be ready
        sleep 10
        
        # Create production core
        curl "http://localhost:8983/solr/admin/cores?action=CREATE&name=blacklight-core-prod&instanceDir=/var/solr/data/blacklight-core-stage&config=solrconfig.xml&schema=schema.xml&dataDir=data" || true
        
        # Wait for precreate to finish
        wait $PRECREATE_PID

  manager:
    container_name: sdoh-manager
    image: herop/sdoh-metadata-manager
    build:
      context: .
    depends_on:
      solr:
        condition: service_healthy
        restart: true
    env_file: .env.docker
    volumes:
      - ./manager:/home/herop/manager
    ports:
    - 8000:8000

volumes:
  solr-data:

