#!/usr/bin/env python3

import pandas as pd

# Mapping of dataset to verify -> master file used for verification
file_map = {
    '2010-tract.csv': 'SVI_2010_US.csv'
}

def read_csv(filepath):
    data = pd.read_csv(filename)
    print(data)
    return data

def report_coverage():
    print('Reporting')

def main():
    print('Running coverage checker...')
    for check, master in dict.items():
        check_list = read_csv(check)
        master_list = read_csv(master)
    print('Done checking!')


if __name__=="__main__":
    main()
